// SERVER CONSTANTS
var KATALON_SERVER_URL_PREFIX = "http://localhost:";
var KATALON_SERVER_URL_SUFFIX = "/"
var XHTTP_GET_METHOD = "GET";
var XHTTP_POST_METHOD = "POST";
var XHTTP_ACTION = "xhttp";

// STYLE CONSTANTS
var ELEMENT_HOVER_OUTLINE_STYLE = "2px solid #f00";

// ANIMATION CONSTANTS
var ELEMENT_FLASHING_OUTLINE_STYLE = "2px solid #0F0"
var ELEMENT_FLASHING_OUTLINE_COLOR_1 = "#FFF";
var ELEMENT_FLASHING_OUTLINE_COLOR_2 = "#0F0";
var ELEMENT_FLASHING_OUTLINE_COLOR_3 = "#F00";